### ISSUE TITLE
can you add an image?

### ISSUE THREAD

**Issue by kacole2** [carone1/ecs-dashboard#1]
can an image be added to the README so users can get an understanding of what is the expected outcome?

**Comment by carone1** [comment]
Yes will add a few images.  Also looking at posting a video on youtube.

**Comment by carone1** [comment]
Screenshot document was added.  
https://github.com/carone1/ecs-dashboard/blob/master/doc/dashboard-screenshots.md

**Comment by carone1** [comment]
Screenshot document was added.  
https://github.com/carone1/ecs-dashboard/blob/master/doc/dashboard-screenshots.md
