### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by kacole2** [carone1/ecs-dashboard#2]
can this all be ran with a series of Dockerfiles? It seems to be pretty intuitive installation process that could be dramatically simplified

**Comment by carone1** [comment]
Agreed. Working on creating docker files for the collector, eraser and emailer.

**Comment by carone1** [comment]
Implemented Ansible playbooks to automate every components of the solution. ElasticSearch, Kibana, Collector, Cleaner and Emailer. See Ansible based instructions in installation guide
